### ISSUE TITLE
Potential modification to ease separation

### ISSUE THREAD

**Issue by smwoodward** [gneu42/Triple-Decky#3]
I printed both the C6_2 and C5_3 of the tophats, mainly to see which one would work better, but something I noticed was I broke one of the end mounts for the BMC gear axel on the first one when clearing the printed supports.  I was able to clear the rest of the supports without problems, but it made me wonder if you were to put a space (similar to the space used between the object and the support to help with removal) between the section of the support that occupies the gear portion of the BMG and the upper part of the support, so that when the support is removed, it breaks in 3 places, top, bottom and middle, this might ease removal of the support along with reducing the risk of breaking the part during removal.

Not sure if it would actually work that way, but just an idea.

**Comment by gneu42** [comment]
This is a good idea. I will try that as soon as I'm back home?
Thanks for the idea.

**Comment by gneu42** [comment]
I've made this new version, can you test it before I upload it on the repo?

![Tophat-revC-new-supports](https://github.com/gneu42/Triple-Decky/assets/59416685/f606586c-90a9-400f-a735-ea97ba7ecda4)

https://www.dropbox.com/scl/fi/nz8lt0ed118amqydt476t/a-Triple_Decky_Tophat-Integrated_For_Magnet_C6_2a.stl?rlkey=g8lirr5x416f54cijhhvoyrhb&dl=0

**Comment by bakatrouble** [comment]
Just tried printing `[a]Triple_Decky_Tophat-Integrated_For_Magnet_C6_3.stl` which contains a similar support structure, and the top section of the three fell out mid-print. I did not have any trouble removing the single-piece support of the 3P servo version.

**Comment by gneu42** [comment]
The previous version is still available in the archive folder. 
   [a]Triple_Decky_Tophat-Integrated_For_Magnet_C6_2.stl
Only the support is different.

**Comment by bakatrouble** [comment]
I went another way, reinforced this separated support with a cylinder primitive in slicer

**Comment by gneu42** [comment]
Stl is changed.
